package za.co.ccos.domain;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * GeneratedNote entity representing a clinical note generated by the system
 */
@Data
@Entity
@Table(name = "generated_notes")
@NoArgsConstructor
@AllArgsConstructor
public class GeneratedNote {
    @Id
    private UUID id;
    
    @Column(nullable = false)
    private UUID consultationId;
    
    private UUID createdBy;
    
    @Column(columnDefinition = "TEXT")
    private String documentationContent;
    
    @Column(columnDefinition = "TEXT")
    private String soapAssessment;
    
    @Column(columnDefinition = "TEXT")
    private String soapSubjective;
    
    @Column(columnDefinition = "TEXT")
    private String soapObjective;
    
    @Column(columnDefinition = "TEXT")
    private String soapPlan;
    
    @Column(columnDefinition = "TEXT")
    private String patientSummary;
    
    private double confidence;
    
    @Column(columnDefinition = "TEXT")
    private String icd10Codes;
    
    @Column(columnDefinition = "TEXT")
    private String suggestedActions;
    
    @Column(columnDefinition = "TEXT")
    private String coordinationActions;
    
    @Column(columnDefinition = "TEXT")
    private String complianceValidation;
    
    @Column(columnDefinition = "TEXT")
    private String perceptionAnalysis;
    
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;
    
    private LocalDateTime updatedAt;
    
    @PrePersist
    protected void onCreate() {
        if (this.id == null) {
            this.id = UUID.randomUUID();
        }
        if (this.createdAt == null) {
            this.createdAt = LocalDateTime.now();
        }
    }
}
